### ISSUE TITLE
ContextData is missing from Media.Event.StateStart events. 

### ISSUE THREAD

**Issue by niemton** [adobe/aepsdk-media-android#27]
### Expected Behaviour
com.adobe.marketing.mobile.MediaTracker#trackEvent should send contextData

### Actual Behaviour
contextData is missing from request. 

### Reproduce Scenario (including but not limited to)
Add contextData to trackEvent that is send from example app
com.adobe.mediaanalyticstestapp.player.PlayerEvent#PLAYER_STATE_MUTE_START. 
Please find code below. 

#### Steps to Reproduce
Mute device when playing content on example app. 

#### Platform and Version
Tested on Android 13 and 14 with com.adobe.marketing.mobile:media 3.0.0

#### Sample Code that illustrates the problem
`
HashMap<String, Object>stateInfo = Media.createStateObject(MediaConstants.PlayerState.MUTE);
				HashMap<String, String> hashMap = new HashMap<>();
				hashMap.put("language", "sv");
				stateInfo.putAll(hashMap);
				_tracker.trackEvent(Media.Event.StateStart, stateInfo, hashMap);
`

#### Logs taken while reproducing problem
Logs show that language is added both event.metadata and event.param. 
`
MobileCore/EventHub - Dispatched Event #28 to extensions after processing rules - ({
                                                                    class: Event,
                                                                    name: Media::TrackMedia,
                                                                    uniqueIdentifier: 416de94f-a53a-47e2-bb92-7edd26fe47c3,
                                                                    source: com.adobe.eventsource.media.trackmedia,
                                                                    type: com.adobe.eventType.media,
                                                                    responseId: null,
                                                                    parentId: null,
                                                                    timestamp: 1697210546902,
                                                                    data: {
                                                                    "event.internal": false,
                                                                    "event.metadata": {
                                                                        "language": "sv"
                                                                    },
                                                                    "trackerid": "5f2f2850-fbdd-4b86-8ca8-7177f10120b3",
                                                                    "event.param": {
                                                                        "state.name": "mute",
                                                                        "language": "sv"
                                                                    },
                                                                    "event.name": "statestart",
                                                                    "sessionid": "3525998e-dddd-4bf6-ab02-1ac683175f63",
                                                                    "event.timestamp": 1697210546901
                                                                },
                                                                    mask: null,
                                                                })
`
Request JSON body is missing language from both params and from customMetadata
`
{
  "playerTime": {
    "playhead": 42,
    "ts": 1697210546902
  },
  "eventType": "stateStart",
  "params": {
    "media.state.name": "mute"
  }
}
`

**Comment by addb** [comment]
Hello @niemton 
The `trackEvent("stateStart")` and `trackEvent("stateEnd")` APIs don't support any additional context data. 

Thanks,
Arjun

**Comment by niemton** [comment]
Thanks for the reply. How then can we send selected track information? It
includes both language and type fields.

pe 13. lokak. 2023 klo 18.57 Arjun Bhadra ***@***.***>
kirjoitti:

**Comment by addb** [comment]
@niemton, There is no way to do this in the trackEvent Player state APIs. How about passing the language with either trackSessionStart or trackEvent(chapterStart) APIs? If you want to request this feature, you can open a Jira ticket for the PMs look at.
